// Generated by dts-bundle v0.4.3

declare module 'phoenix-json-schema-tools' {
    export * from 'phoenix-json-schema-tools/lib/schema';
}

declare module 'phoenix-json-schema-tools/lib/schema' {
    export function checkSchema(schema: any): Promise<void>;
    export function validateObject(value: any, schema: any, options: any): void;
    export function indexesOfSchema(schema: any, addTextIndex: boolean): {
        text?: boolean;
        unique?: boolean;
        fields: string;
    }[];
}

