// Generated by dts-bundle v0.4.3

declare module 'phoenix-json-schema-tools' {
    export var schema: {
        indexesOfSchema: (schema: any, addTextIndex: boolean) => {
            text?: boolean;
            unique?: boolean;
            fields: string;
        }[];
        checkSchema: (schema: any) => Promise<void>;
        enumProps: (value: any, schema: any, cb: (propName: string, propType: string, schema: any, value: any) => void) => void;
        typeOfProperty: (path: string, schema: any) => string;
        pkFields: (schema: any) => string[];
        fields: (schema: any) => string[];
    };
}

